### ISSUE TITLE
System sometimes re-downloads all systems from EDSM and adds them to the database

### ISSUE THREAD

**Issue by travellingkiwi** [EDDiscovery/EDDiscovery-Mac#8]
The database isn't indexed for system uniqueness. So sometimes EDDiscovery will download all the systems from EDSM again... And add them to the database... again... And you end up with multiple times the number of systems that should be there...

I have 5Million at the moment... With v1.10

**Comment by noberasco** [comment]
Hi there,

actually, this issue is more subtle.

EDDiscovery downloads system deltas from EDSM but, instead of merging them with the local data base contents, seems to be inserting all of them regardless of whether they are already present locally.

This seems to happen only if several days have passed since the least systems update...

I think I discovered the culprit. After fetching the system deltas from EDSM, EDDiscovery fetches all the matching systems from the local data base. If the number of delta systems fetched from EDSM is above a certain threshold, the query fails with a SQLITE exception and returns 0 systems, which leads EDDiscovery to think these are all new systems...

I changed the code that fetches the local systems so that it fetches in chunks. This seems to fix the issue...

**Comment by noberasco** [comment]
@travellingkiwi, care to give this commit a test run?

**Comment by travellingkiwi** [comment]
Sure. Soon as I get back from holiday.

However why not simply run a loop in the background (slowly) testing each downloaded system for being already present. if it's not there, add it. If it's different update it...

In the background means we don't care too much how long it takes... I'd like to get all network and file parsing always in the background if possible. Users don't really like waiting... 

Adding a small section on the RHS of the main screen to show what's being done would be good too. i.e. downloading from EDSM. Updating X/Y systems completed. Making it a permanent sidebar and moving the tabs to a subview would be good too that way it would be seen no matter which tab you're on... 

Too much?

**Comment by noberasco** [comment]
Hi,

'slowly' might not be a great idea when you have half a million systems to merge ;-)

However your point is valid, and it matched my first implementation. Problem is, with that approach I kept bumping into SDK bugs (core data bindings for UI elements are apparently not that robust) and in the end I opted to just make the main UI wait until the update had been completed. Note that by combining this patch and patch for issue #7 the parsing speed will be enormously improved, to the point that the bottleneck is now the time EDSM takes to process requests...

**Comment by noberasco** [comment]
Hopefully resolved with 426b0e615d9e3c373d00923e92d0e24c475f5cac
